apiVersion: apps/v1
kind: Deployment

metadata:
  name: ${DEPLOYMENT_NAME}
  labels:
    app: development

spec:
  replicas: 1
  selector:
    matchLabels:
      app: development
  template:
    metadata:
      labels:
        app: development
    spec:
      containers:
        - name: ${DEPLOYMENT_NAME}
          image: ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: GMAIL_SMTP_HOST
              value: "${GMAIL_SMTP_HOST}"
            - name: GMAIL_SMTP_PORT
              value: "${GMAIL_SMTP_PORT}"
            - name: GMAIL_SMTP_USERNAME
              value: "${GMAIL_SMTP_USERNAME}"
            - name: GMAIL_SMTP_PASSWORD
              value: "${GMAIL_SMTP_PASSWORD}"
            - name: TELEGRAM_BOT_USERNAME
              value: "${TELEGRAM_BOT_USERNAME}"
            - name: TELEGRAM_BOT_TOKEN
              value: "${TELEGRAM_BOT_TOKEN}"
            - name: EQUIPMENT_DATASOURCE_HOST
              value: "${EQUIPMENT_DATASOURCE_HOST}"
            - name: EQUIPMENT_DATASOURCE_PORT
              value: "${EQUIPMENT_DATASOURCE_PORT}"
            - name: EQUIPMENT_DATASOURCE_DB
              value: "${EQUIPMENT_DATASOURCE_DB}"
            - name: EQUIPMENT_DATASOURCE_USERNAME
              value: "${EQUIPMENT_DATASOURCE_USERNAME}"
            - name: EQUIPMENT_DATASOURCE_PASSWORD
              value: "${EQUIPMENT_DATASOURCE_PASSWORD}"
          resources:
            requests:
              memory: "1000Mi"
              cpu: "512mm"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
      imagePullSecrets:
        - name: gar-auth
