apiVersion: "v1"
kind: "Service"
metadata:
  name: ${DEPLOYMENT_NAME}-service
  namespace: "default"
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: "development"
spec:
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
      targetPort: 8081
    - name: "https"
      protocol: "TCP"
      port: 443
      targetPort: 8081

  selector:
    app: "development"
  type: "LoadBalancer"
  loadBalancerIP: ${LOAD_BALANCER_IP}