spring:
  datasource:
    url: jdbc:mysql://cets-db.c3oiu0yu842h.us-east-1.rds.amazonaws.com:3306/cets_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hieudt
    password: nmVnlNJBIj9tezKv6vVW
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081