name: Build and Test CI/CD Development Environment

on:
  push:
    branches:
      - feature-dev
  pull_request:
    branches:
      - feature-dev

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    environment: development

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          GMAIL_SMTP_HOST: ${{ secrets.GMAIL_SMTP_HOST }}
          GMAIL_SMTP_PORT: ${{ secrets.GMAIL_SMTP_PORT }}
          GMAIL_SMTP_USERNAME: ${{ secrets.GMAIL_SMTP_USERNAME }}
          GMAIL_SMTP_PASSWORD: ${{ secrets.GMAIL_SMTP_PASSWORD }}
          TELEGRAM_BOT_USERNAME: ${{ secrets.TELEGRAM_BOT_USERNAME }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          EQUIPMENT_DATASOURCE_HOST: ${{ secrets.EQUIPMENT_DATASOURCE_HOST }}
          EQUIPMENT_DATASOURCE_PORT: ${{ secrets.EQUIPMENT_DATASOURCE_PORT }}
          EQUIPMENT_DATASOURCE_DB: ${{ secrets.EQUIPMENT_DATASOURCE_DB }}
          EQUIPMENT_DATASOURCE_USERNAME: ${{ secrets.EQUIPMENT_DATASOURCE_USERNAME }}
          EQUIPMENT_DATASOURCE_PASSWORD: ${{ secrets.EQUIPMENT_DATASOURCE_PASSWORD }}