name: CI

on:
  push:
    branches: [ "main" , "feature-dev" ]
  pull_request:
    branches: [ "main" , "feature-dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [ development, staging, production ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        GMAIL_SMTP_HOST: ${{ vars.GMAIL_SMTP_HOST }}
        GMAIL_SMTP_PORT: ${{ vars.GMAIL_SMTP_PORT }}
        GMAIL_SMTP_USERNAME: ${{ vars.GMAIL_SMTP_USERNAME }}
        GMAIL_SMTP_PASSWORD: ${{ vars.GMAIL_SMTP_PASSWORD }}
