name: CI/CD Development Environment

on:
  push:
    branches: [ "feature-dev" ]
  pull_request:
    branches: [ "feature-dev" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    environment: development

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          GMAIL_SMTP_HOST: ${{ secrets.GMAIL_SMTP_HOST }}
          GMAIL_SMTP_PORT: ${{ secrets.GMAIL_SMTP_PORT }}
          GMAIL_SMTP_USERNAME: ${{ secrets.GMAIL_SMTP_USERNAME }}
          GMAIL_SMTP_PASSWORD: ${{ secrets.GMAIL_SMTP_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-20.04
    environment: development

    permissions:
      contents: read
      id-token: write

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
      DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
      REPOSITORY: ${{ secrets.REPOSITORY }}
      IMAGE: ${{ secrets.IMAGE }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SA_EMAIL: ${{ secrets.SA_EMAIL }}
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF: ${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: authenticate
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SA_EMAIL }}

      - name: Docker Authentication
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.authenticate.outputs.token }}
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Build and Push Docker image
        run: |-
          DOCKER_TAG="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.GITHUB_SHA }}"
          docker build \
            --tag ${DOCKER_TAG} \
            --build-arg GITHUB_SHA="${{ env.GITHUB_SHA }}" \
            --build-arg GITHUB_REF="${{ env.GITHUB_REF }}" \
            .
            docker push ${DOCKER_TAG}
      
      
